### ISSUE TITLE
Cannot add the URL to Redirects

### ISSUE THREAD

**Issue by nyitrairicsi99** [hicham4i/altv-discord-OAuth2-connector#1]
I can't add the following URL to the Redirects page.
`http://resources/discord/html/index.html`
It says "You provided an invalid redirect URI.".

**Comment by hicham4i** [comment]
yeah discord updated their Apps you can no longer add this kind of links 
you can check stuyk he made an updated version of this
> I can't add the following URL to the Redirects page.
> `http://resources/discord/html/index.html`
> It says "You provided an invalid redirect URI.".

**Comment by nyitrairicsi99** [comment]
OK. Thanks.
